version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(batch_id)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    maxBytes: 5000000
    backupCount: 5

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 5000000
    backupCount: 5

loggers:
  src:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]